name: Deploy Noc rlr

on: workflow_dispatch

env:
  AZURE_REGION: eastus2
  RESOURCE_GROUP_NAME: Ignite2022rlr

jobs:

  create_azure_rg:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create Azure RG
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az group create --location ${{ env.AZURE_REGION }} --name ${{ env.RESOURCE_GROUP_NAME }}

  appservice-bicep-template-deploy:
    runs-on: ubuntu-latest
  
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep template
    - name: Deploy Bicep Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        template: ./IaC/deploy-appservice.bicep
        # parameters: appName=<Type a unique name for yor webapp>
        parameters: ./IaC/parameters-appservice.json
